const translation = {
    ptBr: {
        text1: "fólio>",
        text2: "Início",
        text3: "Projetos",
        text4: "Sobre",
        text5: "Contato",
        text6: "Olá,",
        text7: "eu sou",
        text13: "Treino",
        text14: "Conversor de Moedas",
        text15: "Conversor de Real para outras dez moedas. Em breve, vou integrar uma API para captar as cotações do mercado em tempo real.",
        text16: "Sorteador de Números",
        text17: "O sistema sorteia um valor inteiro dentro dos limites definidos pelo usuário, sendo o mínimo inclusivo e o máximo exclusivo.",
        text18: "Cronômetro",
        text19: "Projeto desenvolvido para praticar setInterval e clearInterval. O cronômetro exibe minutos, segundos e milissegundos.",
        text20: "Compras pelo Celular",
        text21: "Página ilustrativa e responsiva para Web e Mobile. (Por enquanto, somente a Home Page).",
        text22: "Cuidamos do seu Pet",
        text23: "Página ilustrativa e responsiva para Web e Mobile. (Por enquanto, somente a Home Page).",
        text24: "Turismo Facilitado",
        text25: "Página ilustrativa, mas responsiva para Mobile em breve. (Por enquanto, somente a Home Page).",
        text26: "Universidade",
        text27: "Algoritmos",
        text28: "Algoritmos desenvolvidos em C para as aulas de Fundamentos de Programação da Universidade.",
        text29: "Sobre Mim",
        text30: "Desenvolvedor em Formação",
        text31: "Meu nome é Renan, tenho 18 anos e estou no primeiro semestre de Sistemas de Informação na UNIFEI. Meu objetivo é me tornar um Desenvolvedor Full Stack e busco complementar minha formação acadêmica com cursos extracurriculares.",
        text32: "Além disso, atuei como enxadrista profissional, conquistando títulos brasileiros e me destacando em torneios internacionais, o que contribuiu para o desenvolvimento do meu raciocínio lógico, criatividade e tomada de decisão acima da média.",
        text33: "Ingressei no DevClub em 05/03/2025 com o objetivo de me tornar Desenvolvedor Full Stack. Ao final de cada conteúdo, desenvolverei diversos projetos utilizando a linguagem aprendida para adicioná-los ao meu portfólio e comprovar meu domínio sobre ela.",
        text34: "Minhas Redes",
        text35: "© 2025 | Desenvolvido por Renan Morais.",
        text36: "Itajubá, Minas Gerais, Brasil",
    }, 
    
    enUs: {
        text1: "folio>",
        text2: "Home",
        text3: "Projects",
        text4: "About",
        text5: "Contact",
        text6: "Hello,",
        text7: "I'm",
        text13: "Training",
        text14: "Currency Converter",
        text15: "Real converter for ten other currencies. Soon, I will integrate an API to capture market quotes in real time",
        text16: "Number Draw",
        text17: "The system draws an integer value within the limits defined by the user, with the minimum being inclusive and the maximum being exclusive.",
        text18: "Stopwatch",
        text19: "Project developed to practice setInterval and clearInterval. The timer displays minutes, seconds and milliseconds.",
        text20: "Easy Shopping Via Mobile",
        text21: "Illustrative and responsive page for Web and Mobile. (For now, only the Home Page).",
        text22: "Pet Care",
        text23: "Illustrative and responsive page for Web and Mobile. (For now, only the Home Page).",
        text24: "Tourism Made Easy",
        text25: "Illustrative page, but responsive for Mobile soon. (For now, only the Home Page).",
        text26: "University",
        text27: "Algorithms",
        text28: "Algorithms developed in C for the University's Programming Fundamentals classes.",
        text29: "About Me",
        text30: "Developer in Training",
        text31: "My name is Renan, I'm 18 years old and I'm in the first semester of Information Systems at UNIFEI. My goal is to become a Full Stack Developer and I seek to complement my academic training with extracurricular courses.",
        text32: "In addition, I worked as a professional chess player, winning Brazilian titles and standing out in international tournaments, which contributed to the development of my logical reasoning, creativity and above-average decision-making.",
        text33: "I joined DevClub on 03/05/2025 with the goal of becoming a Full Stack Developer. At the end of each content, I will develop several projects using the language learned to add them to my portfolio and prove my mastery over it.",
        text34: "My Networks",
        text35: "© 2025 | Developed by Renan Morais.",
        text36: "Itajuba, Minas Gerais, Brazil",
    }
    }

    function translationBRandEN () {
        const selectLanguage = document.querySelector(".linguagem")
        const textToTranslation = document.querySelectorAll("")
    }

selectTranslete.addEventListener("change", translationBRandEN)